Changed Messages layout and fixed Friends list layout
almindor/harbour-jTox pull request #58
Opened 2018-07-22 13:12 UTC by Michal-Szczepaniak

Messages layout is now working without constant use of scrollToBottom and i changed text field behaviour to send messages on enter, lowered it to remove empty space and removed send button since enter sends messages also made header static on top so you dont have to scroll all the way up to see if friend is active.

2018-07-24 15:23 UTC, almindor requested changes
Multi-line sending is required

2018-07-24 15:23 UTC, almindor commented on qml/components/AltInputItem.qml
> +        Keys.onReturnPressed: {
We can't use this. People need to be able to send multi-line messages as per std. messaging clients. The PR looks good otherwise but we need to keep the "push button to send" style. Can you change this section?

2018-07-24 16:35 UTC, Michal-Szczepaniak commented
Sure but i got better idea. If not sure which is better then make it a option is ny motto in gui xD So ill make it an option since i prefer fast short messages i think it will be good solution

2018-07-26 21:56 UTC, Michal-Szczepaniak commented
@almindor Could you review that? It should be okay now

2018-07-27 03:45 UTC, almindor commented
Thanks, will test ASAP and approve if everything seems good.

2018-07-27 04:36 UTC, almindor approved these changes

2018-07-27 04:37 UTC, merged