Chat improvements #71
almindor/harbour-jTox pull request #72
Opened 2019-04-13 20:11 UTC by Michal-Szczepaniak

2019-04-13 20:45 UTC, almindor requested changes
Just coz I'll need it for others too :) you can put it in js/common for example.

2019-04-13 20:45 UTC, almindor commented on qml/components/MessageItem.qml
> +        text: (parseInt(Qt.formatDateTime(created_at, "d")) < parseInt(Qt.formatDateTime(new Date(), "d"))) ?
Could you put this into a function?

2019-04-13 20:48 UTC, Michal-Szczepaniak commented on qml/components/MessageItem.qml
> +        text: (parseInt(Qt.formatDateTime(created_at, "d")) < parseInt(Qt.formatDateTime(new Date(), "d"))) ?
Sure thing

2019-04-14 16:40 UTC, Michal-Szczepaniak commented
Done :)

2019-04-14 19:54 UTC, almindor approved these changes

2019-04-14 19:55 UTC, almindor commented
Oh sorry, I forgot, you'll need to sign your commit.

See [here](https://help.github.com/en/articles/signing-commits) for how to set it up. I think best is to get the signing up and then remake the PR. Sorry for being a PITA but it is after all a security related project.

2019-04-15 09:11 UTC, closed without merging